### ISSUE TITLE
最近解析接口请求头增加了signature现在解析不到了

### ISSUE THREAD

**Issue by tasselx** [jindaxia/plugin.video.rrmj#8]

**Comment by jindaxia** [comment]
@tasselx 好的，我来看一下

**Comment by wilsonwen** [comment]
我也在分析这个问题
反编译apk找到一行code
 SimpleMD5.sha(String.format("ticket=%s&url=%s&randomStr=%s&timestamp=%s", arrayOfObject));

**Comment by jindaxia** [comment]
恩，多谢，SimpleMD5是标准库么 那样的话就好搞

**Comment by wilsonwen** [comment]
sha1加密算法是标准的
不过我试了拼这个signature，还是很难逆向

**Comment by jindaxia** [comment]
把代码贴一下 一起研究下

**Comment by wilsonwen** [comment]
获取视频源的url需要signature字段
`http://api.rr.tv/video/findM3u8ByEpisodeSid`
接口必需的头部字段是:

- token
- t (时间戳)
- signature (校验签名)
- clientType和clientVersion (前三个字段要完全正确，这两个字段稍作修改不影响结果)

body带的必需字段是：

- episodeSid 

**token、t和episodeSid都不能替换，猜测signature是由这三个字段生成；我根据ticket=%s&url=%s&randomStr=%s&timestamp=%s生成字符串，http://www.sha1-online.com/在网站去做sha加密，结果与我截取的signature不一样。目前逆向不出来，主要的问题就是不知道源字符串是怎样组合的。**

**Comment by crzidea** [comment]
求更新

**Comment by tieyingli** [comment]
signature是32位的，应该是md5吧？

**Comment by tieyingli** [comment]
`
             aload1
             ldc "token" (java.lang.String)
             invokestatic com/zhongduomei/rrmj/society/a/g a(()Lcom/zhongduomei/rrmj/society/a/g;);
             getfield com/zhongduomei/rrmj/society/a/g.f:java.lang.String
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "clientVersion" (java.lang.String)
             aload4
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "a" (java.lang.String)
             aload2
             invokestatic com/zhongduomei/rrmj/society/util/InstallationUtils id((Landroid/content/Context;)Ljava/lang/String;);
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "b" (java.lang.String)
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.q:java.lang.String
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "c" (java.lang.String)
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.t:java.lang.String
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "d" (java.lang.String)
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.s:long
             invokestatic java/lang/String valueOf((J)Ljava/lang/String;);
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "e" (java.lang.String)
             getstatic com/zhongduomei/rrmj/society/network/a/c.f:java.lang.String
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.q:java.lang.String
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.t:java.lang.String
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.s:long
             invokestatic com/zhongduomei/rrmj/society/network/volley/a a((Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)Ljava/lang/String;);
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "deviceId" (java.lang.String)
             invokestatic com/zhongduomei/rrmj/society/common/CApplication getContext(()Landroid/content/Context;);
             invokestatic com/zhongduomei/rrmj/society/util/CommonUtils getPhoneImei((Landroid/content/Context;)Ljava/lang/String;);
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.q:java.lang.String
             invokestatic com/zhongduomei/rrmj/society/network/a/c ba(()Ljava/lang/String;);
             invokevirtual java/lang/String equals((Ljava/lang/Object;)Z);
             ifeq L11
             aload0 // reference to self
             invokevirtual com/zhongduomei/rrmj/society/network/volley/a f(()Ljava/util/Map;);
             ldc "episodeSid" (java.lang.String)
             invokeinterface java/util/Map containsKey((Ljava/lang/Object;)Z);
             ifeq L11
             aload0 // reference to self
             invokevirtual com/zhongduomei/rrmj/society/network/volley/a f(()Ljava/util/Map;);
             ldc "quality" (java.lang.String)
             invokeinterface java/util/Map containsKey((Ljava/lang/Object;)Z);
             ifeq L11
             invokestatic java/lang/System currentTimeMillis(()J);
             ldc 28800000 (java.lang.Long)
             lsub
             lstore17
             aload1
             ldc "t" (java.lang.String)
             lload17
             invokestatic java/lang/String valueOf((J)Ljava/lang/String;);
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             ldc "episodeSid=%squality=%sclientType=%sclientVersion=%st=%s" (java.lang.String)
             iconst_5
             anewarray java/lang/Object
             dup
             iconst_0
             aload0 // reference to self
             invokevirtual com/zhongduomei/rrmj/society/network/volley/a f(()Ljava/util/Map;);
             ldc "episodeSid" (java.lang.String)
             invokeinterface java/util/Map get((Ljava/lang/Object;)Ljava/lang/Object;);
             checkcast java/lang/String
             aastore
             dup
             iconst_1
             aload0 // reference to self
             invokevirtual com/zhongduomei/rrmj/society/network/volley/a f(()Ljava/util/Map;);
             ldc "quality" (java.lang.String)
             invokeinterface java/util/Map get((Ljava/lang/Object;)Ljava/lang/Object;);
             checkcast java/lang/String
             aastore
             dup
             iconst_2
             aload8
             aastore
             dup
             iconst_3
             aload4
             aastore
             dup
             iconst_4
             lload17
             invokestatic java/lang/String valueOf((J)Ljava/lang/String;);
             aastore
             invokestatic java/lang/String format((Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;);
             astore20
             new java/lang/StringBuilder
             dup
             invokespecial java/lang/StringBuilder <init>(()V);
             aload20
             invokevirtual java/lang/StringBuilder append((Ljava/lang/String;)Ljava/lang/StringBuilder;);
             ldc "clientSecret=08a30ffbc8004c9a916110683aab0060" (java.lang.String)
             invokevirtual java/lang/StringBuilder append((Ljava/lang/String;)Ljava/lang/StringBuilder;);
             invokevirtual java/lang/StringBuilder toString(()Ljava/lang/String;);
             astore21
             new java/lang/StringBuilder
             dup
             ldc " Signature = " (java.lang.String)
             invokespecial java/lang/StringBuilder <init>((Ljava/lang/String;)V);
             aload21
             invokestatic com/zhongduomei/rrmj/society/util/SimpleMD5 md5((Ljava/lang/String;)Ljava/lang/String;);
             invokevirtual java/lang/StringBuilder append((Ljava/lang/String;)Ljava/lang/StringBuilder;);
             pop
             aload1
             ldc "signature" (java.lang.String)
             aload21
             invokestatic com/zhongduomei/rrmj/society/util/SimpleMD5 md5((Ljava/lang/String;)Ljava/lang/String;);
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop`

**Comment by tieyingli** [comment]
aload1
             ldc "token" (java.lang.String)
             invokestatic com/zhongduomei/rrmj/society/a/g a(()Lcom/zhongduomei/rrmj/society/a/g;);
             getfield com/zhongduomei/rrmj/society/a/g.f:java.lang.String
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "clientVersion" (java.lang.String)
             aload4
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "a" (java.lang.String)
             aload2
             invokestatic com/zhongduomei/rrmj/society/util/InstallationUtils id((Landroid/content/Context;)Ljava/lang/String;);
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "b" (java.lang.String)
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.q:java.lang.String
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "c" (java.lang.String)
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.t:java.lang.String
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "d" (java.lang.String)
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.s:long
             invokestatic java/lang/String valueOf((J)Ljava/lang/String;);
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "e" (java.lang.String)
             getstatic com/zhongduomei/rrmj/society/network/a/c.f:java.lang.String
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.q:java.lang.String
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.t:java.lang.String
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.s:long
             invokestatic com/zhongduomei/rrmj/society/network/volley/a a((Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)Ljava/lang/String;);
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload1
             ldc "deviceId" (java.lang.String)
             invokestatic com/zhongduomei/rrmj/society/common/CApplication getContext(()Landroid/content/Context;);
             invokestatic com/zhongduomei/rrmj/society/util/CommonUtils getPhoneImei((Landroid/content/Context;)Ljava/lang/String;);
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             aload0 // reference to self
             getfield com/zhongduomei/rrmj/society/network/volley/a.q:java.lang.String
             invokestatic com/zhongduomei/rrmj/society/network/a/c ba(()Ljava/lang/String;);
             invokevirtual java/lang/String equals((Ljava/lang/Object;)Z);
             ifeq L11
             aload0 // reference to self
             invokevirtual com/zhongduomei/rrmj/society/network/volley/a f(()Ljava/util/Map;);
             ldc "episodeSid" (java.lang.String)
             invokeinterface java/util/Map containsKey((Ljava/lang/Object;)Z);
             ifeq L11
             aload0 // reference to self
             invokevirtual com/zhongduomei/rrmj/society/network/volley/a f(()Ljava/util/Map;);
             ldc "quality" (java.lang.String)
             invokeinterface java/util/Map containsKey((Ljava/lang/Object;)Z);
             ifeq L11
             invokestatic java/lang/System currentTimeMillis(()J);
             ldc 28800000 (java.lang.Long)
             lsub
             lstore17
             aload1
             ldc "t" (java.lang.String)
             lload17
             invokestatic java/lang/String valueOf((J)Ljava/lang/String;);
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop
             ldc "episodeSid=%squality=%sclientType=%sclientVersion=%st=%s" (java.lang.String)
             iconst_5
             anewarray java/lang/Object
             dup
             iconst_0
             aload0 // reference to self
             invokevirtual com/zhongduomei/rrmj/society/network/volley/a f(()Ljava/util/Map;);
             ldc "episodeSid" (java.lang.String)
             invokeinterface java/util/Map get((Ljava/lang/Object;)Ljava/lang/Object;);
             checkcast java/lang/String
             aastore
             dup
             iconst_1
             aload0 // reference to self
             invokevirtual com/zhongduomei/rrmj/society/network/volley/a f(()Ljava/util/Map;);
             ldc "quality" (java.lang.String)
             invokeinterface java/util/Map get((Ljava/lang/Object;)Ljava/lang/Object;);
             checkcast java/lang/String
             aastore
             dup
             iconst_2
             aload8
             aastore
             dup
             iconst_3
             aload4
             aastore
             dup
             iconst_4
             lload17
             invokestatic java/lang/String valueOf((J)Ljava/lang/String;);
             aastore
             invokestatic java/lang/String format((Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;);
             astore20
             new java/lang/StringBuilder
             dup
             invokespecial java/lang/StringBuilder <init>(()V);
             aload20
             invokevirtual java/lang/StringBuilder append((Ljava/lang/String;)Ljava/lang/StringBuilder;);
             ldc "clientSecret=08a30ffbc8004c9a916110683aab0060" (java.lang.String)
             invokevirtual java/lang/StringBuilder append((Ljava/lang/String;)Ljava/lang/StringBuilder;);
             invokevirtual java/lang/StringBuilder toString(()Ljava/lang/String;);
             astore21
             new java/lang/StringBuilder
             dup
             ldc " Signature = " (java.lang.String)
             invokespecial java/lang/StringBuilder <init>((Ljava/lang/String;)V);
             aload21
             invokestatic com/zhongduomei/rrmj/society/util/SimpleMD5 md5((Ljava/lang/String;)Ljava/lang/String;);
             invokevirtual java/lang/StringBuilder append((Ljava/lang/String;)Ljava/lang/StringBuilder;);
             pop
             aload1
             ldc "signature" (java.lang.String)
             aload21
             invokestatic com/zhongduomei/rrmj/society/util/SimpleMD5 md5((Ljava/lang/String;)Ljava/lang/String;);
             invokevirtual java/util/HashMap put((Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;);
             pop

**Comment by tieyingli** [comment]
`
    public final Map<String, String> d() throws com.android.volley.a {
        HashMap<String, String> hashMap;
        String string2;
        Context context;
        String string;
        block7 : {
            String string3;
            hashMap = new HashMap<String, String>();
            context = (Context)this.r.get();
            if (context == null) {
                return hashMap;
            }
            try {
                String string4;
                string = string4 = context.getPackageManager().getPackageInfo((String)context.getPackageName(), (int)16384).versionName;
            }
            catch (Exception var3_11) {
                var3_11.printStackTrace();
                string = "0";
            }
            String string5 = string3 = "android_" + URLEncoder.encode(c.k, "UTF-8");
            hashMap.put("clientType", string5);
            string2 = string5;
            break block7;
            {
                catch (UnsupportedEncodingException unsupportedEncodingException) {}
            }
            catch (UnsupportedEncodingException unsupportedEncodingException) {
                string5 = "";
                UnsupportedEncodingException unsupportedEncodingException2 = unsupportedEncodingException;
                unsupportedEncodingException2.printStackTrace();
                string2 = string5;
            }
        }
        hashMap.put("token", com.zhongduomei.rrmj.society.a.g.a().f);
        hashMap.put("clientVersion", string);
        hashMap.put("a", InstallationUtils.id((Context)context));
        hashMap.put("b", this.q);
        hashMap.put("c", this.t);
        hashMap.put("d", String.valueOf(this.s));
        hashMap.put("e", a.a((String)c.f, (String)this.q, (String)this.t, (long)this.s));
        hashMap.put("deviceId", CommonUtils.getPhoneImei((Context)CApplication.getContext()));
        if (!this.q.equals(c.ba())) return hashMap;
        if (!this.f().containsKey("episodeSid")) return hashMap;
        if (!this.f().containsKey("quality")) return hashMap;
        long l2 = System.currentTimeMillis() - 28800000;
        hashMap.put("t", String.valueOf(l2));
        String string6 = String.format("episodeSid=%squality=%sclientType=%sclientVersion=%st=%s", (String)this.f().get("episodeSid"), (String)this.f().get("quality"), string2, string, String.valueOf(l2));
        String string7 = string6 + "clientSecret=08a30ffbc8004c9a916110683aab0060";
        new StringBuilder(" Signature = ").append(SimpleMD5.md5((String)string7));
        hashMap.put("signature", SimpleMD5.md5((String)string7));
        return hashMap;
    }
`

**Comment by jindaxia** [comment]
```java
    String string6 = String.format("episodeSid=%squality=%sclientType=%sclientVersion=%st=%s", (String)this.f().get("episodeSid"), (String)this.f().get("quality"), string2, string, String.valueOf(l2));
    String string7 = string6 + "clientSecret=08a30ffbc8004c9a916110683aab0060";
    new StringBuilder(" Signature = ").append(SimpleMD5.md5((String)string7));
    hashMap.put("signature", SimpleMD5.md5((String)string7));
```

**Comment by tieyingli** [comment]
同志们加油哦，我只能帮到这里了

**Comment by jindaxia** [comment]
@wilsonwen signature的算法基本上是确定了，完整的请求是怎样的？

**Comment by tieyingli** [comment]
curl 'https://api.rr.tv/video/findM3u8ByEpisodeSid' -H 'c: lhy' -H 'Cookie: JSESSIONID=FE48725A8ADAE088DDCAD69Dxxxxxxxx' -H 'clientType: ios' -H 'd: 1495874412604' -H 'User-Agent: PUClient/3.5.7 (iPhone; iOS 10.3.2; Scale/2.00)' -H 'clientVersion: 3.5.7' -H 'e: 66e6ea1a5ca9292ae3dab1bbc9000dda949c88c4' -H 't: 1495874412605' -H 'signature: 80175e6685d40c5e20dc581483023541' -H 'Content-Length: 43' -H 'deviceId: 70fe6ea5-d08e-4ed6-985f-3f45bfde2db3' -H 'Connection: keep-alive' -H 'token: xxxxxx0647084927bff7fed4xxxxxxxx' -H 'Accept-Language: zh-Hans-CN;q=1, en-CN;q=0.9' -H 'Accept: */*' -H 'Content-Type: application/x-www-form-urlencoded' -H 'a: 70fe6ea5-d08e-4ed6-985f-3f45bfde2db3' -H 'Accept-Encoding: gzip, deflate' -H 'b: /video/findM3u8ByEpisodeSid' --data 'episodeSid=21423&quality=high&seasonId=1591'  --compressed

**Comment by jindaxia** [comment]
我去看看，这个插件 好久没维护，现在连前面的接口都不出来了。

**Comment by jindaxia** [comment]
@tieyingli https的包用什么工具抓的  我用的Fiddler 抓这些包 有问题

**Comment by tieyingli** [comment]
@jindaxia charles

**Comment by tieyingli** [comment]
@jindaxia 我没有安卓手机，你抓好的包发给我一份吧，谢谢先。我自己也写过一个客户端。比你这个简陋很多

**Comment by tieyingli** [comment]
@jindaxia 我成功了，你加油啊

**Comment by jindaxia** [comment]
@tieyingli 我用Fiddler抓不了https的包，用charles试了一下 是乱码 应该是没有解密。

**Comment by lostsnow** [comment]
@jindaxia 抓 https 需要mitm, 搜一下应该有设置方法 (或者用 mitmproxy 也可以

**Comment by jindaxia** [comment]
Done!

**Comment by wilsonwen** [comment]
Great hack @jindaxia

**Comment by tasselx** [comment]
@tieyingli 
![5103a6dd-9b7d-40ef-9090-0865bece9531](https://user-images.githubusercontent.com/2656142/27187626-4424ea6c-521e-11e7-81ba-fb02796f03e7.png)
如图 t = 1497534015861 episodeSid 55319 quality super clientType ios clientVersion 3.5.8 
md5前的字符串episodeSid=55319quality=superclientType=iosclientVersion=3.5.8t=1497534015861clientSecret=08a30ffbc8004c9a916110683aab0060
md5 后 a5cfc8e45d4619ce7bc52d42e4d5f6b5  跟抓包的不一致是否是clientSecret有改动
还有请教一下是何种方式反汇编到apk的代码的

**Comment by tieyingli** [comment]
@tasselx ios和安卓的clientSecret不一定一致，我用安卓的clientSecret。

**Comment by tasselx** [comment]
@tieyingli 我试过Android的了 clientSecret是一致的 md5后的还是不一致 你那里有请求成功的 md5以前的字符串嘛 能否发来看看

**Comment by PPTing** [comment]
我用了你们上面说的方法在 Headers 里添加了 signature ，但是一直报错
{
    "code": "0002",
    "msg": "视频播放已经全面修复，请升级到最新版本！",
    "data": {}
}

**Comment by jindaxia** [comment]
@PPTing 版本号 不对吧

**Comment by PPTing** [comment]
@jindaxia 版本号 clientVersion 我写的是 3.5.8 也
